dummy:
    image: busybox
    volumes:
     - "$PWD/:/src"
    ports:
     - "80:80"
    environment:
        VIRTUAL_HOST: a.test.com
        VIRTUAL_PATH: /app/kek/
        TEST_VAR: bananas
    command: watch -n 4 date

versionrepeater:
    image: telamon/wharftest-version:1.1.0
    environment:
        VIRTUAL_HOST: what.version.io
        VIRTUAL_PATH: /app/kek/
